version: "3.9"
services:
  video_streamer:
    build: .
    ports:
      - "8501:8501"
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    volumes:
      - ".:/usr/src/"
    command: "streamlit run app_main.py --server.address=0.0.0.0 --server.port=8501"
